# This is a basic workflow to help you get started with Actions

name: Publish sigurd to TestPyPI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install setuptools wheel and twine
      run: >-
        python -m 
        pip install
        --user 
        --upgrade setuptools wheel twine
    - name: Build a binary wheel and a source tarball
      run: >-
        python setup.py sdist bdist_wheel
        
    - name: Publish distribution 📦 to Test PyPI
      run: TWINE_USERNAME="__token__";TWINE_PASSWORD="${{ secrets.test_pypi_password }}"; python -m twine upload --repository testpypi dist/*
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
     
